# Generated by Django 5.1.2 on 2024-11-06 15:17

import django.db.models.deletion
import post.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Роль в игре')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Роль в игре',
                'verbose_name_plural': 'Роли в игре',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Статус поста')),
                ('slug', models.SlugField(unique=True, verbose_name='URL сделки')),
            ],
            options={
                'verbose_name': 'Статус поста',
                'verbose_name_plural': 'Статусы поста',
            },
        ),
        migrations.CreateModel(
            name='TypePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Тип поста')),
                ('slug', models.SlugField(unique=True, verbose_name='URL сделки')),
            ],
            options={
                'verbose_name': 'Тип поста',
                'verbose_name_plural': 'Типы поста',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(max_length=2000, verbose_name='Описание')),
                ('images', models.ImageField(blank=True, upload_to=post.models.images_directory_path)),
                ('published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_post', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('role', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_post', to='post.role', verbose_name='Роль в игре')),
                ('status', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_post', to='post.status', verbose_name='Статус')),
                ('type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_post', to='post.typepost', verbose_name='Тип поста')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
    ]
