# Generated by Django 5.1.2 on 2024-11-06 15:30

import django.db.models.deletion
import post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=post.models.images_directory_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_post', to='post.role', verbose_name='Роль в игре'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_post', to='post.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_post', to='post.typepost', verbose_name='Тип поста'),
        ),
    ]
