# Generated by Django 5.1.2 on 2024-11-13 09:41

import django.db.models.deletion
import team.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название команды')),
                ('body', models.TextField(max_length=2000, verbose_name='Описание')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=team.models.images_directory_path)),
                ('social_url', models.TextField(max_length=2000, verbose_name='Сайт команды')),
                ('published', models.BooleanField(default=True, verbose_name='Активна')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_team', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('teammates', models.ManyToManyField(related_name='teammates', to=settings.AUTH_USER_MODEL, verbose_name='Участники команды')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
    ]
