# Generated by Django 5.1.2 on 2024-11-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='body',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='team',
            name='social_url',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Сайт команды'),
        ),
    ]
