# Generated by Django 5.1.2 on 2025-01-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_servertype_thirdpartyserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdpartyserver',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
    ]
