# Generated by Django 5.1.2 on 2024-11-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='url',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Ссылка переход'),
        ),
    ]
