# Generated by Django 5.1.2 on 2025-01-22 09:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0002_advert_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniNews',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Сама мини новость')),
                ('url', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Ссылка переход')),
                ('published', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mininews_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Мини новости',
                'verbose_name_plural': 'Мини новости',
            },
        ),
    ]
