# Generated by Django 5.1.2 on 2025-03-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0003_mininews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название блока'),
        ),
    ]
