# Generated by Django 5.1.2 on 2024-12-23 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raffle',
            options={'verbose_name': 'Розыгрыш', 'verbose_name_plural': 'Розыгрыши'},
        ),
        migrations.AlterModelOptions(
            name='skin',
            options={'verbose_name': 'Скин', 'verbose_name_plural': 'Скины'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Тикет', 'verbose_name_plural': 'Тикеты'},
        ),
    ]
