# Generated by Django 5.1.2 on 2025-01-13 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0003_remove_skin_total_tickets_remove_ticket_skin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='raffle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raffle.raffle'),
        ),
    ]
