# Generated by Django 5.1.2 on 2025-02-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0004_alter_ticket_raffle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skin',
            name='image_url',
            field=models.CharField(max_length=255),
        ),
    ]
