# Generated by Django 5.1.2 on 2025-03-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0005_alter_skin_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skin',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
