# Generated by Django 5.1.2 on 2025-04-01 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0006_alter_skin_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('reward', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Награда')),
                ('task_type', models.CharField(choices=[('daily', 'Ежедневное'), ('username', 'Изменение имени'), ('subscribe', 'Подписка'), ('custom', 'Другое условие')], default='daily', max_length=20, verbose_name='Тип задания')),
                ('condition', models.TextField(blank=True, null=True, verbose_name='Условие (ссылка)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
            ],
        ),
        migrations.AlterField(
            model_name='raffle',
            name='end_time',
            field=models.DateTimeField(verbose_name='Время конца'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='is_drawn',
            field=models.BooleanField(default=False, verbose_name='Разыгран'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='remaining_tickets',
            field=models.PositiveIntegerField(default=100, verbose_name='Билетов доступно'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='skin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raffles', to='raffle.skin', verbose_name='Скин'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='total_tickets',
            field=models.PositiveIntegerField(default=100, verbose_name='Билетов всего'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_raffles', to=settings.AUTH_USER_MODEL, verbose_name='Победитель'),
        ),
        migrations.AlterField(
            model_name='skin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='skin',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='skin',
            name='image_url',
            field=models.CharField(max_length=510, verbose_name='Ссылка на картинку'),
        ),
        migrations.AlterField(
            model_name='skin',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='skin',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='skin',
            name='price_in_tickets',
            field=models.IntegerField(verbose_name='Стоимость, если 0 то бесплатный'),
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raffle.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
