# Generated by Django 5.1.2 on 2025-04-03 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0007_task_alter_raffle_end_time_alter_raffle_is_drawn_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AlterModelOptions(
            name='usertask',
            options={'verbose_name': 'Выполненное задание', 'verbose_name_plural': 'Выполненные задания'},
        ),
    ]
