# Generated by Django 5.1.2 on 2025-04-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrenadeThrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название раскидки')),
                ('grenade_type', models.CharField(choices=[('smoke', 'Smoke'), ('flash', 'Flash')], max_length=10, verbose_name='Тип гранаты')),
                ('map_name', models.CharField(max_length=50, verbose_name='Название карты')),
                ('description', models.TextField(verbose_name='Описание')),
                ('video_webm_url', models.URLField(verbose_name='Ссылка на WebM-видео')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Граната',
                'verbose_name_plural': 'Гранаты',
            },
        ),
    ]
