# Generated by Django 5.1.2 on 2025-01-13 10:57

import useraccount.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_user_balance_user_steam_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background_profile',
            field=models.ImageField(blank=True, null=True, upload_to=useraccount.models.backgrounds_directory_path),
        ),
        migrations.AddField(
            model_name='user',
            name='trade_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
