# Generated by Django 5.1.2 on 2025-01-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0006_alter_promocode_amount_alter_promocode_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
