# Generated by Django 5.1.2 on 2025-01-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0007_alter_promocode_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='is_used',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='user',
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Дата окончания'),
        ),
    ]
