# Generated by Django 5.1.2 on 2025-02-05 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0008_remove_promocode_is_used_remove_promocode_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinBuyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_name', models.CharField(max_length=255)),
                ('steam_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('approved', 'Одобрено'), ('bought', 'Выкуплено'), ('paid', 'Оплачено'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
