# Generated by Django 5.1.2 on 2025-02-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0011_alter_user_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skinbuyorder',
            name='steam_price',
        ),
        migrations.AddField(
            model_name='skinbuyorder',
            name='asset_id',
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skinbuyorder',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='skinbuyorder',
            name='payment_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skinbuyorder',
            name='trade_offer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
