# Generated by Django 5.1.2 on 2025-02-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0012_remove_skinbuyorder_steam_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skinbuyorder',
            name='asset_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='ID предмета в Steam'),
        ),
        migrations.AlterField(
            model_name='skinbuyorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='skinbuyorder',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='skinbuyorder',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='skinbuyorder',
            name='payment_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка оплаты'),
        ),
        migrations.AlterField(
            model_name='skinbuyorder',
            name='skin_name',
            field=models.CharField(max_length=255, verbose_name='Название скина'),
        ),
        migrations.AlterField(
            model_name='skinbuyorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('approved', 'Одобрено'), ('bought', 'Выкуплено'), ('paid', 'Оплачено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='skinbuyorder',
            name='trade_offer_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Трейд оффер'),
        ),
    ]
