# Generated by Django 5.1.2 on 2025-02-18 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0013_alter_skinbuyorder_asset_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоды'},
        ),
        migrations.AlterModelOptions(
            name='skinbuyorder',
            options={'verbose_name': 'Скупка', 'verbose_name_plural': 'Скупка'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
