# Generated by Django 5.1.2 on 2025-03-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0014_alter_promocode_options_alter_skinbuyorder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skinbuyorder',
            name='image_url',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Картинка'),
        ),
    ]
