# Generated by Django 5.1.2 on 2025-03-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0015_alter_skinbuyorder_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skinbuyorder',
            name='asset_id',
            field=models.CharField(max_length=50, verbose_name='ID предмета в Steam'),
        ),
    ]
