# Generated by Django 5.1.2 on 2025-03-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0016_alter_skinbuyorder_asset_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skinbuyorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('approved', 'Отправлено'), ('accepted', 'Принято'), ('bought', 'Выкуплено'), ('paid', 'Оплачено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
