# Generated by Django 5.1.2 on 2025-03-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0017_alter_skinbuyorder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skinbuyorder',
            name='payment_url',
        ),
        migrations.AddField(
            model_name='skinbuyorder',
            name='payment_id',
            field=models.CharField(blank=True, null=True, verbose_name='id оплаты'),
        ),
    ]
